/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ClaimsIndexRouteImport } from './routes/claims.index'
import { Route as ClaimsBatchRouteImport } from './routes/claims.batch'
import { Route as ClaimsSingleRouteImport } from './routes/claims.single'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersBatchRouteImport } from './routes/providers.batch'
import { Route as ProvidersSingleRouteImport } from './routes/providers.single'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsIndexRoute = ClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsBatchRoute = ClaimsBatchRouteImport.update({
  id: '/claims/batch',
  path: '/claims/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsSingleRoute = ClaimsSingleRouteImport.update({
  id: '/claims/single',
  path: '/claims/single',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersBatchRoute = ProvidersBatchRouteImport.update({
  id: '/providers/batch',
  path: '/providers/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSingleRoute = ProvidersSingleRouteImport.update({
  id: '/providers/single',
  path: '/providers/single',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/claims/batch': typeof ClaimsBatchRoute
  '/claims/single': typeof ClaimsSingleRoute
  '/providers/batch': typeof ProvidersBatchRoute
  '/providers/single': typeof ProvidersSingleRoute
  '/claims/': typeof ClaimsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/claims/batch': typeof ClaimsBatchRoute
  '/claims/single': typeof ClaimsSingleRoute
  '/providers/batch': typeof ProvidersBatchRoute
  '/providers/single': typeof ProvidersSingleRoute
  '/claims': typeof ClaimsIndexRoute
  '/providers': typeof ProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/claims/batch': typeof ClaimsBatchRoute
  '/claims/single': typeof ClaimsSingleRoute
  '/providers/batch': typeof ProvidersBatchRoute
  '/providers/single': typeof ProvidersSingleRoute
  '/claims/': typeof ClaimsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/claims/batch'
    | '/claims/single'
    | '/providers/batch'
    | '/providers/single'
    | '/claims/'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/claims/batch'
    | '/claims/single'
    | '/providers/batch'
    | '/providers/single'
    | '/claims'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/claims/batch'
    | '/claims/single'
    | '/providers/batch'
    | '/providers/single'
    | '/claims/'
    | '/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  ClaimsBatchRoute: typeof ClaimsBatchRoute
  ClaimsSingleRoute: typeof ClaimsSingleRoute
  ProvidersBatchRoute: typeof ProvidersBatchRoute
  ProvidersSingleRoute: typeof ProvidersSingleRoute
  ClaimsIndexRoute: typeof ClaimsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/': {
      id: '/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof ClaimsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/batch': {
      id: '/claims/batch'
      path: '/claims/batch'
      fullPath: '/claims/batch'
      preLoaderRoute: typeof ClaimsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/single': {
      id: '/claims/single'
      path: '/claims/single'
      fullPath: '/claims/single'
      preLoaderRoute: typeof ClaimsSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/batch': {
      id: '/providers/batch'
      path: '/providers/batch'
      fullPath: '/providers/batch'
      preLoaderRoute: typeof ProvidersBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/single': {
      id: '/providers/single'
      path: '/providers/single'
      fullPath: '/providers/single'
      preLoaderRoute: typeof ProvidersSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  ClaimsBatchRoute: ClaimsBatchRoute,
  ClaimsSingleRoute: ClaimsSingleRoute,
  ProvidersBatchRoute: ProvidersBatchRoute,
  ProvidersSingleRoute: ProvidersSingleRoute,
  ClaimsIndexRoute: ClaimsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
